version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: explorandes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ardara123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explorandes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ardara123
    depends_on:
      - postgres

volumes:
  postgres-data: