version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: explorandes-db
    environment:
      POSTGRES_DB: explorandes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ardara123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: explorandes-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explorandes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ardara123
      - SPRING_PROFILES_ACTIVE=init-data
      - DD_AGENT_HOST=host.docker.internal
      - DD_AGENT_PORT=8126
    volumes:
      - app-uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  app-uploads: