version: '3'

services:
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    network_mode: "host"  # Use host network instead of bridge
    environment:
      - DD_API_KEY=ddd
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=env:development,service:explorandes-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw

  postgres:
    image: postgres:15
    container_name: explorandes-postgres
    network_mode: "host"  # Use host network
    environment:
      POSTGRES_DB: explorandes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ardara123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: explorandes-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explorandes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ardara123
      - DD_AGENT_HOST=localhost
      - DD_AGENT_PORT=8126
      - DD_ENV=development
      - DD_SERVICE=explorandes-backend
      - DD_VERSION=1.0.0
      - DD_TRACE_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_SITE=us5.datadoghq.com
      # This is critical - pass the API key explicitly
      - MANAGEMENT_DATADOG_METRICS_EXPORT_API_KEY=ddd
    networks:
      - explorandes-network
    depends_on:
      - postgres
      - datadog-agent
    labels:
      com.datadoghq.ad.logs: '[{"source":"java","service":"explorandes-backend"}]'

    # ensure your Dockerfile copies dd‑java‑agent.jar into the image at /
    command: >
      java \
        -javaagent:/dd-java-agent.jar \
        -Ddd.agent.host=${DD_AGENT_HOST} \
        -Ddd.agent.port=${DD_AGENT_PORT} \
        -jar app.jar

networks:
  explorandes-network:
    driver: bridge

